services:
  - type: web
    name: crypto-tracker-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: crypto-tracker-db
          property: connectionString
    healthCheckPath: /api/health
